Add `plasma_physics` module for 0-D plasma physics tools
Fusion-Power-Plant-Framework/bluemira pull request #1112
Opened 2022-06-01 13:11 UTC by CoronelBuendia

## Linked Issues

Does this PR close or fix any Issues? Remember to create an Issue before starting work so that your fix / proposal can be addressed by the team.

e.g. Closes #{ID}

## Description

What is your PR trying to achieve? How did you go about achieving it?

## Interface Changes

If you've had to update an interface or introduce a new interface as part of your change then let us know here.

## Checklist

I confirm that I have completed the following checks:

- [ ] Tests run locally and pass `pytest tests --reactor`
- [ ] Code quality checks run locally and pass `flake8` and `black .`
- [ ] Documentation built locally and checked `sphinx-build -W documentation/source documentation/build`

2022-06-07 13:00 UTC, hsaunders1904 approved these changes
Looks fine to me, just one typing correction

2022-06-07 14:56 UTC, CoronelBuendia commented
> I had one thought about the location of this. If as the title suggests it just contains tools would a better location be a submodule `plasma_physics` to utilities? Or are we likely to run into dependency loops if we do that?

Tools is perhaps a bad word to have used... At the moment this might seem rather small to have as a module, but I anticipate growth - not least from #1086 

I don't know about dependency loops yet, and can't foresee what they would be like once this gets padded out with other stuff.

This seemed philosophically different enough from utilities, and specific enough to our "brief" to potentially warrant a new module. Unlike e.g. ML tools which are really generic and less directly relevant to our brief.

I'm not fussy about this though - right now it's barely used.

2022-06-07 14:58 UTC, je-cook commented
Sure if its going to grow that makes sense, was just a thought

2022-06-08 12:25 UTC, je-cook requested changes
Just some units things

2022-06-08 12:25 UTC, je-cook commented on bluemira/plasma_physics/scaling_laws.py
> +    n = n * 1e19  # [10^19/m^3]
same here actually, I think this is the wrong way round should probably do this:
```suggestion
    n = raw_uc(n, '1/m^3', '1e19/m^3')  # [10^19/m^3]
```

2022-06-08 12:25 UTC, je-cook commented on bluemira/plasma_physics/scaling_laws.py
> +    n_e20 = n_e / 1e20
possibly overkill but:
```suggestion
    n_e20 = raw_uc(n_e,  '1/m^3', '1e20/m^3')
```

2022-06-09 14:44 UTC, je-cook approved these changes
Great last test :smile:

2022-06-10 07:48 UTC, CoronelBuendia commented
> Great last test smile

Actually come to think of the ITER confinement time should be around 3 seconds.. not 1! Probably messed up the inputs. I did it a bit whimsically...

2022-06-10 10:39 UTC, merged