Spherical Harmonics
Fusion-Power-Plant-Framework/bluemira pull request #1128
Opened 2022-06-09 12:57 UTC by markj997

## Description

Implementation of necessary functions, constraints, examples, etc, enabling use of spherical harmonics for optimisation and solving of equilibria.

2022-06-10 07:38 UTC, je-cook requested changes
Looks good! Just some code styling things mostly, also one about where the loop should start

2022-06-10 07:38 UTC, je-cook commented on bluemira/equilibria/flux_surfaces.py
> +    return amplitudes
Just fyi the '@' symbol I think accomplished the same thing (uses matmul under the hood) also you could just directly return the calculation eg 
```suggestion
    return currents2harmonics @ I_f
```

2022-06-10 07:38 UTC, je-cook commented on bluemira/equilibria/opt_constraints.py
> +        x_f, z_f = coil.x, coil.z
Is this not just getting the x and z of the last coil in the coilset?
```python
coil = eq.coilset[-1]
x_f, z_f = coil.x, coil.z
```

2022-06-10 13:32 UTC, sebkahn requested changes

2022-06-10 13:32 UTC, sebkahn commented on bluemira/equilibria/opt_constraints.py
> +    # we just extract I_f from the eq object within the function?
The equilibrium gets update at each grad-Shafranov iteration by definition.

As far as I understand the GS does not get updated with the PF optimization, however the coilset by definition should. Although I am not fully aware of the implentation details @alexanderianblair ?

2022-06-10 13:35 UTC, je-cook commented on bluemira/equilibria/flux_surfaces.py
> +import scipy.constants as const
bluemira ones please. They all come from the same place which is the 2018 codata database. We get that via Pint just so we get them all from the same package

2022-06-10 13:37 UTC, je-cook commented on bluemira/equilibria/opt_constraints.py
> +        x_f, z_f = coil.x, coil.z
Cant remember, but I can make it so in the refactor. For now your suggestion is probably the right way forward

2022-06-10 13:39 UTC, je-cook commented on bluemira/equilibria/flux_surfaces.py
> +
https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-math :slightly_smiling_face:

2022-06-10 13:55 UTC, sebkahn commented
Good first pass, we should put the constraints on `opt_constraitns_funcs.py`

2023-04-25 13:47 UTC, CoronelBuendia commented
Closing in favour of #1963

2023-04-25 13:47 UTC, closed without merging