ADR for caching
Fusion-Power-Plant-Framework/bluemira pull request #1196
Opened 2022-07-01 08:10 UTC by CoronelBuendia

## Linked Issues

Does this PR close or fix any Issues? Remember to create an Issue before starting work so that your fix / proposal can be addressed by the team.

e.g. Closes #{ID}

## Description

What is your PR trying to achieve? How did you go about achieving it?

## Interface Changes

If you've had to update an interface or introduce a new interface as part of your change then let us know here.

## Checklist

I confirm that I have completed the following checks:

- [ ] Tests run locally and pass `pytest tests --reactor`
- [ ] Code quality checks run locally and pass `flake8` and `black .`
- [ ] Documentation built locally and checked `sphinx-build -W documentation/source documentation/build`

2022-07-01 08:11 UTC, CoronelBuendia commented on documentation/developer/adr/0005-record-cache-vs-recreate.md
> +Date: 2022-06-14
cmon man...

2022-11-30 14:04 UTC, CoronelBuendia commented
@je-cook @hsaunders1904 @ivanmaione let me know what you think, conscious we should get this in not too long after the caching merge!

2022-11-30 14:33 UTC, je-cook requested changes
Looks fine generally just a couple of comments

2022-11-30 14:33 UTC, je-cook commented on documentation/developer/adr/0005-record-cache-vs-recreate.md
> +# 1. Record architecture decisions
```suggestion
# 5. Caching vs recreation of geometry
```

2022-11-30 14:33 UTC, je-cook commented on documentation/developer/adr/0005-record-cache-vs-recreate.md
> +
Maybe a comment here that it may be possible to revisit this in future with FreeCAD V1 when its released

2022-12-02 17:31 UTC, je-cook approved these changes

2022-12-09 15:29 UTC, ivanmaione commented
@CoronelBuendia , @je-cook , not sure if this is the right place, but we should mention that the recreation problem is not totally avoided (hopefully just simplified) since we want/need to serialize/deserialize objects. What is your opinion?

2022-12-09 16:09 UTC, je-cook commented
Yeah this is the place for that kind of information

2022-12-14 23:18 UTC, merged