✨ Radiation Shield new designer
Fusion-Power-Plant-Framework/bluemira pull request #1369
Opened 2022-08-26 08:51 UTC by je-cook

## Description

TODO testing

## Interface Changes

If you've had to update an interface or introduce a new interface as part of your change then let us know here.

## Checklist

I confirm that I have completed the following checks:

- [ ] Tests run locally and pass `pytest tests --reactor`
- [ ] Code quality checks run locally and pass `flake8` and `black .`
- [ ] Documentation built locally and checked `sphinx-build -W documentation/source documentation/build`

2022-09-05 10:02 UTC, je-cook commented
#1351 should go in before this

2022-09-06 14:51 UTC, hsaunders1904 requested changes
Looks like some debugging code has been leftover - otherwise looks good to me

2022-09-06 15:15 UTC, je-cook commented on bluemira/builders/radiation_shield.py
> +        show_cad([self.cryo_vv, cryo_vv_rot])
Oops yeah!

2022-09-13 07:57 UTC, hsaunders1904 approved these changes
One suggestion for something to add to the test, but otherwise LGTM

2022-09-13 07:57 UTC, hsaunders1904 commented on tests/builders/test_radiation_shield.py
> +        assert len(xyz.leaves) == self.params["n_TF"]["value"]
Could we add a `show_cad` call on the `xyz` component?

2022-09-13 08:29 UTC, merged