Fix SonarCloud bugs that cause all PRs to fail when merged into `develop`
Fusion-Power-Plant-Framework/bluemira pull request #1463
Opened 2022-09-22 15:43 UTC by CoronelBuendia

## Linked Issues

Does this PR close or fix any Issues? Remember to create an Issue before starting work so that your fix / proposal can be addressed by the team.

e.g. Closes #{ID}

## Description

What is your PR trying to achieve? How did you go about achieving it?

## Interface Changes

If you've had to update an interface or introduce a new interface as part of your change then let us know here.

## Checklist

I confirm that I have completed the following checks:

- [ ] Tests run locally and pass `pytest tests --reactor`
- [ ] Code quality checks run locally and pass `flake8` and `black .`
- [ ] Documentation built locally and checked `sphinx-build -W documentation/source documentation/build`

2022-09-23 08:16 UTC, hsaunders1904 approved these changes

2022-09-26 06:50 UTC, je-cook requested changes
Just one thing otherwise fine

2022-09-26 06:50 UTC, je-cook commented on bluemira/structural/model.py
> +        return False
There seems like a lot of warnings here now (there were anyway). As this function is only called once in the whole code (on line 431) can the error that if statement produces be put here too or something similar?

2022-09-26 07:46 UTC, je-cook approved these changes

2022-09-26 08:15 UTC, merged