EUDEMO reactor starting point
Fusion-Power-Plant-Framework/bluemira pull request #1658
Opened 2022-11-24 14:25 UTC by hsaunders1904

## Linked Issues

Closes #{ID}

## Description

Some working builds

## Interface Changes

## Checklist

I confirm that I have completed the following checks:

- [ ] Tests run locally and pass `pytest tests --reactor`
- [ ] Code quality checks run locally and pass `flake8` and `black .`
- [ ] Documentation built locally and checked `sphinx-build -W documentation/source documentation/build`

2022-11-24 14:48 UTC, CoronelBuendia approved these changes

2022-11-25 07:17 UTC, je-cook requested changes
Looks great! Just a few things that probably didnt come over in a rebase I think

2022-11-25 09:06 UTC, je-cook commented on examples/design/EU-DEMO/EUDEMO_builders/power_cycle.py
> -# bluemira is an integrated inter-disciplinary design tool for future fusion
I think the whole design folder is gone and the rest of the files have just been moved: https://github.com/Fusion-Power-Plant-Framework/bluemira/tree/635c369845233f5af35dab739b0964310f3c5a3f/examples

2022-11-25 10:17 UTC, je-cook approved these changes
Happy once the tests run

2022-11-25 11:01 UTC, hsaunders1904 commented
OK, I've got nothing more to add to this, I don't think. Tests aren't expected to pass at this point, but they're now running.

2022-11-25 13:35 UTC, merged