🐛 fix indexing bug in inscribed_rect test
Fusion-Power-Plant-Framework/bluemira pull request #1707
Opened 2022-12-07 13:53 UTC by je-cook

## Description

When trying to catch errors the indexing wasnt nested deep enough.
This is very hard to see if it fixes the occasional failure we see because I haven't had a local failing example

## Interface Changes

## Checklist

I confirm that I have completed the following checks:

- [ ] Tests run locally and pass `pytest tests --reactor`
- [ ] Code quality checks run locally and pass `flake8` and `black .`
- [ ] Documentation built locally and checked `sphinx-build -W documentation/source documentation/build`

2022-12-08 06:19 UTC, CoronelBuendia requested changes
5% failure rate before this PR:
```python
>   if not all([get_area(*t.xyz) == 0.0 for t in tf]):
E   AttributeError: 'list' object has no attribute 'xyz'
```

4% failure rate with this PR:
```python
.0 = <list_iterator object at 0x7f0581b83b80>

        [
>           get_area(*seg.xyz) <= self.MIN_AREA
            for t in tf
            for seg in t
        ]
    ):
E   AttributeError: 'numpy.ndarray' object has no attribute 'xyz'

```

(Rates on 100 runs. There are 5 tests in file, so 500 tests, so technically a lower failure rate in terms of tests)

2022-12-08 08:52 UTC, je-cook commented
Getting there! Ok I'll have another go

2022-12-08 16:44 UTC, CoronelBuendia commented
5 failures in 100 runs:

```python
tests/geometry/test_inscribed_rect.py:100: in <listcomp>
    Coordinates(seg.discretize(byedges=True, ndiscr=50))
bluemira/geometry/coordinates.py:1244: in __init__
    self._array = _parse_to_xyz_array(xyz_array)
bluemira/geometry/coordinates.py:1143: in _parse_to_xyz_array
    xyz_array = _parse_array(xyz_array)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

xyz_array = array([[[ 3.59999968,  0.        , -4.99999844],
        [ 3.59999968,  0.        , -4.99999856],
        [ 3.59999968...    , -4.99999868],
        [ 3.5999997 ,  0.        , -4.99999856],
        [ 3.59999968,  0.        , -4.99999844]]])

    def _parse_array(xyz_array):
        try:
            xyz_array = np.array(np.atleast_2d(xyz_array), dtype=np.float64)
        except ValueError:
            raise CoordinatesError(
                "Cannot instantiate Coordinates with a ragged (3, N | M) array."
            )
    
        shape = xyz_array.shape
        if len(shape) > 2:
>           raise NotImplementedError
E           NotImplementedError

bluemira/geometry/coordinates.py:1159: NotImplementedError
```

I think you need to treat the point and 0 length segments properly somehow..

2022-12-12 08:05 UTC, je-cook commented
I ran it 500 times and got no failures, but then again I didnt get many before so its probably worth another check

2022-12-12 09:44 UTC, merged