Add simple `PFCoilSupportBuilder` (updated)
Fusion-Power-Plant-Framework/bluemira pull request #1946
Opened 2023-02-17 13:29 UTC by CoronelBuendia

## Linked Issues

Closes #{ID}

## Description

## Interface Changes

## Checklist

I confirm that I have completed the following checks:

- [ ] Tests run locally and pass `pytest tests --reactor`
- [ ] Code quality checks run locally and pass `flake8` and `black .`
- [ ] Documentation built locally and checked `sphinx-build -W documentation/source documentation/build`

2023-02-17 13:31 UTC, CoronelBuendia commented
Still need to add mroe tests but based off of #1942

2023-02-27 10:49 UTC, je-cook requested changes
Looks good will run now just to see locally, a few little things

2023-02-27 10:49 UTC, je-cook commented on tests/builders/test_coil_supports.py
> +    )
ParameterFrame needs setting up as in #1942, I will get round to fixing #1947 soon...

2023-02-27 10:49 UTC, je-cook commented on bluemira/builders/coil_supports.py
> +            return None
This automatically happens as there is nothing past this point
```suggestion
```

2023-02-27 10:49 UTC, je-cook commented on bluemira/builders/coil_supports.py
> +
```suggestion
            if not np.dot(correct_direction, direction) < 0:
```

2023-02-27 13:22 UTC, je-cook approved these changes

2023-02-27 13:22 UTC, merged