✨ Fenicx upgrade
Fusion-Power-Plant-Framework/bluemira pull request #2872
Opened 2023-12-12 10:18 UTC by je-cook

## Description

Based off FreeCAD PR, still needs a bit of work to update the tests. Also the precision issue we've talked about at length.

## Interface Changes

## Checklist

I confirm that I have completed the following checks:

- [ ] Tests run locally and pass `pytest tests --reactor`
- [ ] Code quality checks run locally and pass `pre-commit run --from-ref develop --to-ref HEAD`
- [ ] Documentation built locally and checked `sphinx-build -W documentation/source documentation/build`

2024-02-29 15:37 UTC, je-cook reviewed
I can't approve this as I opened the PR @oliverfunk can you give this a look over at your next opportunity.

2024-03-19 16:18 UTC, oliverfunk requested changes
I've left review comments on what I know about and can review.

Genrally the sctructure looks good. There are a number of slightly concerning type issues.

For ex. "BluemiraFemFunction" is used synonimously with some fenicx class.

It's probably not a big issue though.

Otherwise looking mostly good!

2024-03-19 16:24 UTC, je-cook commented on examples/equilibria/fem_fixed_boundary/fem_boundary_conditions_example.py
> +    LCFS = cntr.get_paths()[0].vertices
you need to update matplotlib and then the error goes away

2024-03-19 16:26 UTC, je-cook commented on examples/magnetostatics/finite_element_2D_single_coil.ex.py
> +# |_  |
I was trying to represent the shape that is created. I'll expand the comment

2024-03-20 11:23 UTC, je-cook commented on bluemira/equilibria/fem_fixed_boundary/utilities.py
>      return interp1d(x, profile_data, kind="linear", fill_value="extrapolate")
L112 and L113 of file.py

2024-03-20 11:34 UTC, je-cook commented on bluemira/equilibria/fem_fixed_boundary/utilities.py
> +        psi_array = psi_func(points)
Could do but I think we should do that as part of a wider cleanup of types

2024-03-20 12:02 UTC, je-cook commented on examples/codes/equilibrium_plasmod_example.ex.py
>      iter_err_max=1e-3,
This is ok its because the centre tricontour doesnt exist (because its too small)

2024-03-20 12:06 UTC, je-cook commented on bluemira/magnetostatics/fem_utils.py
> +def convert_to_points_array(x):
done

2024-03-20 12:06 UTC, je-cook commented on bluemira/magnetostatics/biot_savart.py
> +#  application of Biot-Savart to a filament coil
done

2024-03-20 12:06 UTC, je-cook commented on bluemira/equilibria/fem_fixed_boundary/fem_magnetostatic_2D.py
>              a = r * pprime(x_psi)
added a protection

2024-03-20 12:06 UTC, je-cook commented on bluemira/magnetostatics/fem_utils.py
> +def calculate_area(mesh: Mesh, boundaries: object, tag: Optional[int] = None) -> float:
done

2024-03-20 12:38 UTC, oliverfunk approved these changes
I'm happy

2024-03-20 13:04 UTC, merged