WIP: Separatrix mods for up/down split
Fusion-Power-Plant-Framework/bluemira pull request #2944
Opened 2024-01-18 11:11 UTC by geograham

## Description

Current code is written assuming in/out split for the double null separatrix list found using find_LCFS_separatrix. 
Relevant Functions have been modified to allow for an up/down split. 

I confirm that I have completed the following checks:

- [ ] Tests run locally and pass `pytest tests --reactor`
- [ ] Code quality checks run locally and pass `pre-commit run --from-ref develop --to-ref HEAD`
- [ ] Documentation built locally and checked `sphinx-build -W documentation/source documentation/build`

2024-02-01 14:46 UTC, geograham commented on bluemira/equilibria/find.py
> +        # Double null (N.B., always sort resulting leg dict by in/out
Ok, no problem, will split it up and try to make it clearer.

2024-02-15 17:35 UTC, CoronelBuendia requested changes
Really quick review from my side... apologies have not had time to look at the actual algorithm or play around with it. Just a couple of minor first impressions

2024-02-16 11:01 UTC, geograham commented on bluemira/equilibria/find.py
> +    rtol: float = 1e-2,
thanks for spotting, have changed it back

2024-02-27 16:42 UTC, CoronelBuendia approved these changes

2024-02-29 09:05 UTC, je-cook reviewed
Looks good just one minor

2024-03-04 11:30 UTC, je-cook approved these changes
Couple of quick fixes otherwise good to go!

2024-03-04 11:30 UTC, je-cook commented on bluemira/equilibria/find_legs.py
> +                return NumNull["DN".upper()], SortSplit["Z".upper()]
```suggestion
                return NumNull.DN, SortSplit.Z
```

2024-03-04 11:30 UTC, je-cook commented on bluemira/equilibria/find_legs.py
> +            return NumNull["DN".upper()], SortSplit["X".upper()]
```suggestion
            return NumNull.DN, SortSplit.X
```

2024-03-04 11:30 UTC, je-cook commented on bluemira/equilibria/find_legs.py
> +        return NumNull["SN".upper()], SortSplit["X".upper()]
```suggestion
        return NumNull.SN, SortSplit.X
```

2024-03-04 11:32 UTC, je-cook commented
I don't know what up with the CI...everything passes locally

2024-03-04 12:52 UTC, merged