Urgent fix coil type
Fusion-Power-Plant-Framework/bluemira pull request #3036
Opened 2024-02-21 12:59 UTC by athoynilimanew

## Linked Issues

Fixes duplication of CoilType Enum

Closes #{ID}

## Description

## Interface Changes

## Checklist

I confirm that I have completed the following checks:

- [ ] Tests run locally and pass `pytest tests --reactor`
- [ ] Code quality checks run locally and pass `pre-commit run --from-ref develop --to-ref HEAD`
- [ ] Documentation built locally and checked `sphinx-build -W documentation/source documentation/build`

2024-02-22 14:37 UTC, geograham requested changes

2024-02-22 14:37 UTC, geograham commented on bluemira/equilibria/coils/coil_type.py
Could you write a simple test for the CoilType class?

2024-02-22 14:37 UTC, geograham commented on bluemira/equilibria/coils/_coil.py
This is probably a silly question, but could you explain why CoilType needed to be moved to a separate file? Is it a circular import error related to plotting.py?

2024-02-22 14:39 UTC, athoynilimanew commented on bluemira/equilibria/coils/_coil.py
Exactly. Somehow plotting.py and pf_coil.py were talking to each other and it was the source of circular error

2024-02-22 16:15 UTC, athoynilimanew commented on bluemira/equilibria/coils/coil_type.py
added in the latest commit.

2024-02-22 16:49 UTC, geograham approved these changes

2024-02-27 09:06 UTC, je-cook requested changes
This is not ready. I think there were a few things missing from the review of #3021 on top of that. I will start with comments there and come back here.

2024-02-27 13:42 UTC, je-cook requested changes
On top of the comments in #3021 I think the coils enum should be moved to base. I think moving it either to constants.py or its own file in base. I'm unsure of the exact location but generally inside the base module

2024-02-28 13:30 UTC, athoynilimanew commented
> On top of the comments in #3021 I think the coils enum should be moved to base. I think moving it either to constants.py or its own file in base. I'm unsure of the exact location but generally inside the base module

Moved to constants.py and accordingly changed the imports. moved test function as well

2024-02-28 13:31 UTC, athoynilimanew commented
> This is not ready. I think there were a few things missing from the review of #3021 on top of that. I will start with comments there and come back here.

Applied/responded to all required changes (see #3021 for additional comments)

2024-02-29 12:45 UTC, je-cook commented on bluemira/equilibria/equilibrium.py
> +            if vcontrol_type is VerticalPositionControlType.FEEDBACK:
I think probably more robust is the below as we haven't dealt with any other control type
```suggestion
            else:
```

2024-02-29 12:49 UTC, je-cook commented on bluemira/geometry/coordinates.py
> +
```suggestion
         else:
             raise NotImplementedError
```

2024-02-29 12:50 UTC, je-cook commented on bluemira/geometry/tools.py
>          plane_idxs = (1, 2)
```suggestion
    elif hull_plane is HullPlaneType.YZ:
        plane_idxs = (1, 2)
    else: 
        raise NotImplementedError
```

2024-02-29 15:07 UTC, je-cook approved these changes

2024-02-29 15:07 UTC, merged