Papercut type fixes
Fusion-Power-Plant-Framework/bluemira pull request #3053
Opened 2024-02-27 17:34 UTC by geograham

## Linked Issues

Papercut #3022

## Checklist

I confirm that I have completed the following checks:

- [ ] Tests run locally and pass `pytest tests --reactor`
- [ ] Code quality checks run locally and pass `pre-commit run --from-ref develop --to-ref HEAD`
- [ ] Documentation built locally and checked `sphinx-build -W documentation/source documentation/build`

2024-02-29 08:59 UTC, je-cook requested changes
Thanks for being the guinea pig on this, I will add any stylistic decisions to the issue that come out of this PR once we've all agreed

2024-03-05 14:14 UTC, je-cook commented on bluemira/equilibria/fem_fixed_boundary/fem_magnetostatic_2D.py
> +    def set_mesh(self, mesh: Union[dolfin.Mesh, str]) -> None:
Ok I've had a chat, a search and a think and I think we should remove the None return type when there is no return (implicit return) like above.

2024-03-11 17:39 UTC, je-cook commented on bluemira/equilibria/boundary.py
> +    def __call__(self, psi: npt.NDArray[np.float64], jtor: npt.NDArray[np.float64]):
Urr thanks for looking into it. I feel thats a numpy problem... How about `npt.NDArray[np.float_]` as you put somewhere?

2024-03-11 17:55 UTC, geograham commented on bluemira/equilibria/boundary.py
> +    def __call__(self, psi: npt.NDArray[np.float64], jtor: npt.NDArray[np.float64]):
Our pre-commit seems to automatically change npt.NDArray[np.float_] to npt.NDArray[np.float64].

2024-03-12 09:12 UTC, je-cook approved these changes

2024-03-12 09:12 UTC, je-cook commented on bluemira/equilibria/optimisation/constraint_funcs.py
> +        def f_constraint(self, vector: npt.NDArray[np.float_]) -> npt.NDArray[np.float_]:
```suggestion
        def f_constraint(self, vector: npt.NDArray[np.float64]) -> npt.NDArray[np.float64]:
```

2024-03-12 09:12 UTC, je-cook commented on bluemira/equilibria/optimisation/constraint_funcs.py
> +        def df_constraint(self, vector: npt.NDArray[np.float_]) -> npt.NDArray[np.float_]:
```suggestion
        def df_constraint(self, vector: npt.NDArray[np.float64]) -> npt.NDArray[np.float64]:
```

2024-03-12 09:12 UTC, je-cook commented on bluemira/equilibria/optimisation/objectives.py
> +        def f_objective(self, vector: npt.NDArray[np.float_]) -> npt.NDArray[np.float_]:
```suggestion
        def f_objective(self, vector: npt.NDArray[np.float64]) -> npt.NDArray[np.float64]:
```

2024-03-12 09:12 UTC, je-cook commented on bluemira/equilibria/optimisation/objectives.py
> +        def df_objective(self, vector: npt.NDArray[np.float_]) -> npt.NDArray[np.float_]:
```suggestion
        def df_objective(self, vector: npt.NDArray[np.float64]) -> npt.NDArray[np.float64]:
```

2024-03-12 09:35 UTC, geograham commented on bluemira/equilibria/boundary.py
> +    def __call__(self, psi: npt.NDArray[np.float64], jtor: npt.NDArray[np.float64]):
No worries!

2024-03-12 09:46 UTC, merged