Adding toroidal harmonic notebooks
Fusion-Power-Plant-Framework/bluemira pull request #3681
Opened 2024-10-28 16:15 UTC by clmould

## Linked Issues

Closes #{ID}

## Description

## Interface Changes

## Checklist

I confirm that I have completed the following checks:

- [ ] Tests run locally and pass `pytest tests --reactor`
- [ ] Code quality checks run locally and pass `pre-commit run --from-ref develop --to-ref HEAD`
- [ ] Documentation built locally and checked `sphinx-build -W documentation/source documentation/build`

2024-11-04 11:45 UTC, je-cook reviewed
From my naive understand looks really good. Could have have some tests for the function going into the main package please?

2024-11-14 14:49 UTC, geograham requested changes

2024-11-18 08:01 UTC, je-cook commented
I was just running our tests on develop and we get a warning from one of the conversion functions (from arccos of a number outside the range `-1<x>1` could we add a np.clip to this line unless that would have unintended side effects?

https://github.com/Fusion-Power-Plant-Framework/bluemira/blob/fcce20f4d6d08157a1902c88ea00b4d48a1655dd/bluemira/utilities/tools.py#L867

to 

```python
np.clip((d_1**2 + d_2**2 - 4 * R_0**2) / (2 * d_1 * d_2), -1, 1)
```
this seem to remove the warning in my quick test.

2024-12-12 14:54 UTC, je-cook approved these changes
From a code perspective looks good, thanks for adding the tests. A few little things otherwise from my end good to go. 

I can't comment on the actual maths maybe @CoronelBuendia or @geograham can comment more?

2024-12-12 14:54 UTC, je-cook commented on examples/equilibria/single_wire_field_toroidal_harmonics.ex.py
> +
```suggestion
%%
```

2024-12-12 14:54 UTC, je-cook commented on examples/equilibria/single_wire_field_toroidal_harmonics.ex.py
> +single_wire_image = Image.open("single_wire_output_image.png")
This file doesnt seem to exist

2024-12-12 14:54 UTC, je-cook commented on bluemira/equilibria/optimisation/harmonics/toroidal_harmonics_approx_functions.py
> +def my_legendre_p(lam, mu, x, n_max=20):
Could we remove the "my_" from the function names now we're no longer testing? Here, any use and the 'my_legrende_q' below
```suggestion
def legendre_p(lam, mu, x, n_max=20):
```

2024-12-13 16:11 UTC, geograham approved these changes
Looks good to go

2024-12-13 16:11 UTC, geograham commented on bluemira/equilibria/optimisation/harmonics/toroidal_harmonics_approx_functions.py
> +        argument required for f_hypergeometric.
```suggestion
        upper value for summation in f_hypergeometric.
```

2024-12-13 16:11 UTC, geograham commented on bluemira/equilibria/optimisation/harmonics/toroidal_harmonics_approx_functions.py
> +        argument required for f_hypergeometric.
```suggestion
        upper value for summation in f_hypergeometric.
```

2024-12-16 11:14 UTC, merged