Eq analysis tools update
Fusion-Power-Plant-Framework/bluemira pull request #3692
Opened 2024-11-12 14:54 UTC by geograham

## Description

Further additions/updates for the eq analysis feature branch.

See examples/equilibria/anaylsis_toolbox_examples.ex.py for how to use.

## Checklist

I confirm that I have completed the following checks:

- [x] Tests run locally and pass `pytest tests --reactor`
- [x] Code quality checks run locally and pass `pre-commit run --from-ref develop --to-ref HEAD`
- [x] Documentation built locally and checked `sphinx-build -W documentation/source documentation/build`

2025-01-17 08:23 UTC, je-cook reviewed
Thanks for this, I've done an initial run through as this is getting quite large. Could we get some tests the make the plots you've added?

2025-01-17 08:23 UTC, je-cook commented on examples/equilibria/eudemo_2017.ex.py
> +    relaxation=0.2,
Remove the trailing comma here and the other Iterator change

2025-01-17 08:23 UTC, je-cook commented on examples/equilibria/anaylsis_toolbox_examples.ex.py
> +# SPDX-License-Identifier: LGPL-2.1-or-later
```suggestion
# ---
#   jupytext:
#     cell_metadata_filter: tags,-all
#     notebook_metadata_filter: -jupytext.text_representation.jupytext_version
#     text_representation:
#       extension: .py
#       format_name: percent
#       format_version: '1.3'
#   kernelspec:
#     display_name: Python 3 (ipykernel)
#     language: python
#     name: python3
# ---
# %% tags=["remove-cell"]
# SPDX-FileCopyrightText: 2021-present M. Coleman, J. Cook, F. Franza
# SPDX-FileCopyrightText: 2021-present I.A. Maione, S. McIntosh
# SPDX-FileCopyrightText: 2021-present J. Morris, D. Short
#
# SPDX-License-Identifier: LGPL-2.1-or-later
```

2025-01-17 08:23 UTC, je-cook commented on bluemira/equilibria/solve.py
> +        ax.semilogy([0, len(self.progress)], [self.limit, self.limit])
Repeat axis definition

2025-01-17 08:23 UTC, je-cook commented on bluemira/equilibria/find_legs.py
> +                if leg[0] is not None:
```suggestion
            if len(leg) > 0 and leg[0] is not None:
```

2025-01-23 14:43 UTC, je-cook commented
This should solve all the conflicts easily `git rebase --onto feature/eq_analysis_tools bd84305`. After that I will reset the feature branch to this point so that all your new things are contained within this PR, unless you think otherwise?: 
![image](https://github.com/user-attachments/assets/bf52496c-74c2-4f3e-aa65-d643655b002d)

2025-01-23 15:54 UTC, je-cook requested changes
On the whole really cool. I've been through it all once and run the two examples. We can have a hat about any of this that seems no necessarily straight forward.

I've commented on the example for when I would like the style adjusted or added to, it was easier than tracking it down in the code...

2025-01-23 15:54 UTC, je-cook commented on examples/equilibria/eudemo_2017.ex.py
> +    psi_diff=False, split_psi_plots=False, reference_eq=reference_eq
split_psi_plots is a bool here but this fails when running the notebook on plotting L742

2025-01-23 15:54 UTC, je-cook commented on tests/equilibria/test_analysis.py
> +        "legs_to_plot", [DivLegsToPlot.ALL, DivLegsToPlot.UP, DivLegsToPlot.LW]
ALL and UP fail for me locally

ALL: AssertionError: assert 2 == 4
UP: One of your chosen equilibria does not have upper_inner legs.

2025-01-23 15:54 UTC, je-cook commented on examples/equilibria/anaylsis_toolbox_examples.ex.py
> +eq_analysis_1.plot_profiles()
The axes labels here are x and z, that doesnt seem right to me?

2025-01-23 15:54 UTC, je-cook commented on examples/equilibria/anaylsis_toolbox_examples.ex.py
> +ax = eq_analysis_1.plot_compare_separatrix()
Could we get axis equal set on this figure, it seems at least locally thats not been set in some instances although I can see it in xz_plot_setup.

2025-01-23 15:54 UTC, je-cook commented on examples/equilibria/anaylsis_toolbox_examples.ex.py
> +ax = eq_analysis_1.plot_target_flux(
Same with this please, equal axes, actually all of the x/z plots

2025-01-23 15:54 UTC, je-cook commented on examples/equilibria/anaylsis_toolbox_examples.ex.py
> +ax = multi_analysis.plot_compare_profiles()
Could we have some units on the ones that need it (I'm thinking pressure),

2025-01-23 15:54 UTC, je-cook commented on examples/equilibria/anaylsis_toolbox_examples.ex.py
> +eq_analysis_2.plot_compare_psi()
this colour bar seems artificially limited in some way here
![image](https://github.com/user-attachments/assets/3eac4b10-bdc6-4253-b310-df2e9f159e8a)

2025-01-23 15:54 UTC, je-cook commented on examples/equilibria/anaylsis_toolbox_examples.ex.py
> +eq_analysis_2.plot_compare_psi()
also could we get some units and a title for this colour bar

2025-01-23 15:54 UTC, je-cook commented on bluemira/equilibria/plotting.py
> +            self.ax[0].set_aspect("equal")
This seems to be repeated quite a few times across these changes can we abstract it into some helper function? (with title as input?)

2025-01-23 15:54 UTC, je-cook commented on bluemira/equilibria/analysis.py
> +    from bluemira.equilibria.optimisation.problem.base import CoilsetOptimisationProblem
can we move this block to the bottom of the imports and sort the result?

2025-01-23 15:54 UTC, je-cook commented on bluemira/equilibria/analysis.py
> +import pandas as pd
Pandas at the moment is a transient dependency. How much do you use it?

2025-01-23 15:54 UTC, je-cook commented on bluemira/equilibria/analysis.py
> +        self.to_cocos = (3,)
Are these meant to be tuples?

2025-01-23 15:54 UTC, je-cook commented on bluemira/equilibria/analysis.py
> +        dx = np.ones(n_layers) * x
There is a dz above too (I may have got the arguments the wrong way around)
```suggestion
        dx = np.full(n_layers, x)
```

2025-01-23 15:54 UTC, je-cook commented on bluemira/equilibria/analysis.py
> +        fs_list.append(fs)
```suggestion
        fs_list.append(Coordinates({"x": fs_x[select_idx], "z": fs_z[select_idx]}))
```

2025-01-23 15:54 UTC, je-cook commented on bluemira/equilibria/analysis.py
> +        dataframe.columns = [self.eq_name]
we could possibly use tabulate if this is the main use of pandas, let me know and I'll find a snippet

2025-01-23 15:54 UTC, je-cook commented on bluemira/equilibria/analysis.py
> +        prof_dict = {
This feels like the perfect use for a dataclass rather than a dictionary.

2025-02-04 15:25 UTC, geograham commented on tests/equilibria/test_analysis.py
> +        "legs_to_plot", [DivLegsToPlot.ALL, DivLegsToPlot.UP, DivLegsToPlot.LW]
Thanks for spotting, should have tested for a raised error here, this is done now

2025-02-04 15:26 UTC, geograham commented on bluemira/equilibria/analysis.py
> +        dataframe.columns = [self.eq_name]
All pandas removed

2025-02-05 10:46 UTC, geograham commented on bluemira/equilibria/plotting.py
> +        except Exception:  # noqa: BLE001
I think an EquilibriaError could be appropriate. I'll add a TODO.

2025-02-05 10:49 UTC, geograham commented on bluemira/equilibria/plotting.py
> +        if (self.ref_total_psi - self.ref_plasma_psi == 0).all():
Thank you, good spot

2025-02-05 12:54 UTC, oliverfunk commented on bluemira/equilibria/coils/_field.py
> +            same_pos = np.nonzero(xw.any() == zw.any())[0]
I pretty sure this is not intended. .any() returns a single True/False, not any array where it's true/false in the correct positions. But I could misreading it.

2025-02-05 13:02 UTC, oliverfunk commented on bluemira/equilibria/equilibrium.py
> +        return forces[self.coilset._control_ind, :]
me too

2025-02-05 13:03 UTC, oliverfunk commented on bluemira/equilibria/optimisation/problem/_minimal_current.py
> +        self.plotting_enabled = plot
So this would be the pattern applied to all COP's? Could maybe go into the super class then

2025-02-05 14:20 UTC, geograham commented on examples/equilibria/anaylsis_toolbox_examples.ex.py
> +eq_analysis_2.plot_compare_psi()
Thanks - vmin and vmax where set to total psi rather than component psi values

2025-02-05 14:37 UTC, oliverfunk commented on bluemira/equilibria/plotting.py
> +    def interpolate_psi_for_comparison(self):
These should made _

Because they set the class's state and are used only on init.

THey're not part of the public api

2025-02-05 14:44 UTC, oliverfunk commented on bluemira/utilities/plot_tools.py
> +    if folder is None:
Ok i'm not sure about this. I think we want to try avoid the use of generate_data for pip install reasons.

2025-02-05 14:49 UTC, oliverfunk commented on bluemira/equilibria/analysis.py
> +def select_eq(
Is this really nec? It just wrapping .from_eqdsk

I don't really understand the rename coilset call at the bottom either.

`eq.coilset = rename_coilset(eq.coilset)` is counter-intuitive

2025-02-05 14:51 UTC, oliverfunk reviewed
So far looks good, I need to run it and play with it more.

2025-02-05 15:38 UTC, geograham commented on bluemira/equilibria/equilibrium.py
> +        return forces[self.coilset._control_ind, :]
I have simplified this with broadcasting as suggested by James. The two changes are to avoid matrices with incompatible shapes, if you run the analysis_toolbox_examples notebook, the problem crops up using MultiEqAnalysis to get coilset info (last couple of cells).

2025-02-05 15:50 UTC, geograham commented on bluemira/equilibria/analysis.py
> +def select_eq(
This is to deal with the coil number counter, it keeps all the coil names consistent when you are comparing multiple equilibria.

2025-02-05 15:54 UTC, geograham commented on bluemira/utilities/plot_tools.py
> +    if folder is None:
What do you reckon as an alternative?

2025-02-05 16:03 UTC, geograham commented on bluemira/equilibria/plotting.py
> +
This could potentially be modified to remove the iterable ax, we would need to change the plotting sections which use GridSpec for plotting.

2025-02-06 12:01 UTC, geograham commented on bluemira/equilibria/coils/_field.py
> +            same_pos = np.nonzero(xw.any() == zw.any())[0]
Thanks for spotting, I have reworked this section in the latest commit.

2025-02-10 10:47 UTC, geograham commented on bluemira/utilities/plot_tools.py
> +    if folder is None:
added a TODO as wider issue

2025-02-10 11:21 UTC, je-cook reviewed
A few more

2025-02-10 11:21 UTC, je-cook commented on bluemira/equilibria/analysis.py
> +def make_table(data, column_names):
Contemplating moving this function to eg utilities/tools...

2025-02-10 11:21 UTC, je-cook commented on bluemira/equilibria/analysis.py
> +        return table
This will be a string which is not hugely accessible for the user, possibly returning eq_summaries is better?

2025-02-10 11:21 UTC, je-cook commented on examples/equilibria/anaylsis_toolbox_examples.ex.py
> +eq_analysis_1.plot_eq_core_mag_axis()
It would be good to detail what the solid and dotted red lines are somewhere on the plot (a legend, or in a heading of some type)

2025-02-10 11:21 UTC, je-cook commented on examples/equilibria/anaylsis_toolbox_examples.ex.py
> +core_results, ax = eq_analysis_1.plot_eq_core_analysis(ax=None)
Units for R0, area, V(?)

2025-02-10 11:21 UTC, je-cook commented on examples/equilibria/anaylsis_toolbox_examples.ex.py
> +ax = multi_analysis.plot_divertor_length_angle(
Not sure I understand this one

2025-02-10 13:23 UTC, geograham commented on bluemira/equilibria/analysis.py
> +def make_table(data, column_names):
In  that case should I also move rename_coilset across to plot tools as well?

2025-02-10 13:47 UTC, je-cook commented on bluemira/equilibria/analysis.py
> +def make_table(data, column_names):
yeah, possibly rename_coilset could go into the equilibria coils folder instead of going to utilitites/tools

2025-02-10 13:55 UTC, oliverfunk commented on examples/equilibria/anaylsis_toolbox_examples.ex.py
> +eq_analysis_1.plot()
I find this quite confusing as you're call .plot() on the eq analysis object.
The EqAnalysis obj effectively takes two equ. as input.
It's not clear which is being plotted here

2025-02-17 13:19 UTC, geograham commented on examples/equilibria/anaylsis_toolbox_examples.ex.py
> +ax = multi_analysis.plot_divertor_length_angle(
Added more x axis label to plot and more details in notebook of examples.

2025-02-17 13:20 UTC, geograham commented on examples/equilibria/anaylsis_toolbox_examples.ex.py
> +eq_analysis_1.plot()
Added Eq as optional input for every function as discussed in person.

2025-02-17 13:27 UTC, geograham commented on examples/equilibria/anaylsis_toolbox_examples.ex.py
> +eq_analysis_1.plot_eq_core_mag_axis()
Added legend

2025-02-17 13:28 UTC, geograham commented on examples/equilibria/anaylsis_toolbox_examples.ex.py
> +core_results, ax = eq_analysis_1.plot_eq_core_analysis(ax=None)
Changed to tuple

2025-02-17 13:48 UTC, geograham commented on bluemira/equilibria/coils/_field.py
> +            same_pos = np.full(shape=x.size, fill_value=False)
Yes, that's right

2025-02-25 15:02 UTC, oliverfunk approved these changes

2025-02-25 15:48 UTC, merged