Save TF Shape
Fusion-Power-Plant-Framework/bluemira pull request #628
Opened 2022-01-20 18:13 UTC by DanShort12

## Linked Issues

N/A

## Description

This PR supports saving the TF Coils builder shape (and any other shape builders) to a json file.

## Interface Changes

Adds `save_shape` to `ParameterisedShapeBuilder`.

## Checklist

I confirm that I have completed the following checks:

- [x] Tests run locally and pass `pytest tests --reactor`
- [x] Code quality checks run locally and pass `flake8` and `black .`
- [x] Documentation built locally and checked `sphinx-build -W documentation/source documentation/build`

2022-01-24 07:34 UTC, CoronelBuendia requested changes
I think this might need a rebase? I'm pretty sure a lot of this came in with #622

2022-01-24 16:19 UTC, DanShort12 commented on bluemira/builders/EUDEMO/tf_coils.py
> +        if self._geom_path is not None and os.path.isdir(self._geom_path):
Tweaked the validation to account for this.

2022-01-24 16:20 UTC, DanShort12 commented
Needs already committed commits to be removed.

2022-01-24 16:46 UTC, DanShort12 commented
Rebase should now have just the relevant files.

2022-01-25 09:27 UTC, CoronelBuendia approved these changes

2022-01-25 09:27 UTC, merged