Hook up steady-state `BalanceOfPlant` to `EUDEMO/reactor.py`
Fusion-Power-Plant-Framework/bluemira pull request #707
Opened 2022-02-11 10:38 UTC by CoronelBuendia

## Description

Adds in an interface to the simplified steady-state balance of plant model in `balance_of_plant` for the EU-DEMO reactor example.

## Interface Changes

Probably some to come

## Checklist

I confirm that I have completed the following checks:

- [ ] Tests run locally and pass `pytest tests --reactor`
- [x] Code quality checks run locally and pass `flake8` and `black .`
- [ ] Documentation built locally and checked `sphinx-build -W documentation/source documentation/build`

2022-04-19 07:44 UTC, je-cook reviewed
Conceptually looks fine, l think your json merge conflict commit went a bit wrong

2022-04-19 07:44 UTC, je-cook commented on tests/builders/EUDEMO/template.json
> -=======
It looks like you deleted too much here?

2022-04-19 07:44 UTC, je-cook commented on tests/builders/EUDEMO/template.json
> -    "source": "Input (HCPB 2015 design description document 2MHDNB)"
Wrong source deleted here possibly

2022-04-20 08:12 UTC, je-cook requested changes
There may be others but I thought this was autogenerated?

2022-04-20 08:12 UTC, je-cook commented on tests/builders/EUDEMO/template.json
> +    "unit": "Pam^3/s",
```suggestion
    "unit": "Pa m^3/s",
```

2022-04-20 08:12 UTC, je-cook commented on tests/builders/EUDEMO/template.json
>      "source": "Calculated"
```suggestion
    "source": "Calculated",
```

2022-05-30 09:23 UTC, je-cook approved these changes
I'm happy here, dunno whether @hsaunders1904 wants this to go in before or after the solvers refactor that he's doing

2022-06-06 12:50 UTC, hsaunders1904 approved these changes
A couple of minor things, but looks good to me otherwise. Happy for it to be merged.

Changes to the solver interface won't be too major, I'll resolve any conflicts that may arise. 

I did spot a `numpy` deprecation warning whilst running one of the examples, although I don't think it was caused by new code in this PR. I'll open a separate ticket to sort that.

2022-06-09 14:28 UTC, CoronelBuendia commented
@hsaunders1904 just rebased for now - potentially badly, will pick up comments tomorrow

2022-06-10 06:05 UTC, CoronelBuendia commented on bluemira/builders/EUDEMO/power_cycle.py
> +            f_vessel=params.vvpfrac.value,  # TODO: Change this parameter name
Yes, these are fair comments. My hesitation came from the fact that we are actively discussed how best to manage `Parameter`s that are solely used in one place (i.e. not really globals). Furthermore for these power fractions we technically need a reduced or surrogate neutronics model to determine the neutron power deposited in the various components. I didn't want to bring in my crude volumetric approach prior to the neutronics team having a crack at it.

2022-06-10 13:26 UTC, je-cook commented on bluemira/builders/EUDEMO/power_cycle.py
> +            f_vessel=params.vvpfrac.value,  # TODO: Change this parameter name
Could put it as a note here: https://github.com/Fusion-Power-Plant-Framework/bluemira/projects/21

2022-06-13 08:22 UTC, merged