Add `value_at` method to `BluemiraWire` for primitive point finding and interpolation
Fusion-Power-Plant-Framework/bluemira pull request #813
Opened 2022-03-15 13:13 UTC by CoronelBuendia

## Linked Issues

Closes #799 

## Description
Adds a `value_at` method to `BluemiraWire` which can take either an alpha or distance and return a point, working using direct primitive interpolation, rather than discretised interpolation.

## Interface Changes

`find_point_at_distance_along_wire` was deprecated

## Checklist

I confirm that I have completed the following checks:

- [x] Tests run locally and pass `pytest tests --reactor`
- [x] Code quality checks run locally and pass `flake8` and `black .`
- [x] Documentation built locally and checked `sphinx-build -W documentation/source documentation/build`

2022-03-15 14:08 UTC, hsaunders1904 requested changes
Code looks good to me. Just a couple of comments on the tests

2022-03-15 16:27 UTC, CoronelBuendia commented
Thanks for those @hsaunders1904 hopefully covered now

2022-03-17 10:14 UTC, hsaunders1904 approved these changes

2022-03-17 11:25 UTC, ivanmaione approved these changes

2022-03-17 13:39 UTC, je-cook approved these changes

2022-03-17 13:39 UTC, merged