a bit stucjk
Fusion-Power-Plant-Framework/bluemira pull request #814
Opened 2022-03-15 15:21 UTC by CoronelBuendia

## Linked Issues

Does this PR close or fix any Issues? Remember to create an Issue before starting work so that your fix / proposal can be addressed by the team.

e.g. Closes #{ID}

## Description

What is your PR trying to achieve? How did you go about achieving it?

## Interface Changes

If you've had to update an interface or introduce a new interface as part of your change then let us know here.

## Checklist

I confirm that I have completed the following checks:

- [ ] Tests run locally and pass `pytest tests --reactor`
- [ ] Code quality checks run locally and pass `flake8` and `black .`
- [ ] Documentation built locally and checked `sphinx-build -W documentation/source documentation/build`

2022-03-18 12:23 UTC, CoronelBuendia commented
@shaildesai96 some TF builder base class changes coming in here. Keep an eye out for when this gets merged in. I can help if anything breaks, but it should just be a couple of name changes.

2022-03-18 17:07 UTC, alexanderianblair requested changes
Nothing major - nice to see the same framework being used.

Main points are to communicate the similarities between the implementation of `OptimisationProblem` here and in Equilibria

2022-03-18 17:07 UTC, alexanderianblair commented on bluemira/geometry/optimisation.py
> +        parameterisation: GeometryParameterisation,
Possibly worth calling this input `geometry_parameterisation` to make it a little clearer to a reader the difference in usage between this and _parameterisation (although I know that they will reference the same object after the super().__init__ call).

2022-03-21 08:05 UTC, CoronelBuendia commented on bluemira/geometry/optimisation.py
> +def minimise_length(vector, grad, parameterisation, ad_args=None):
Yes, I did hesitate to put one in.. I have tried in the past to make a decorator that does this, but it got a bit fiddly (I can't remember why exactly). Perhaps we can do this in a separate PR.

2022-03-21 12:52 UTC, alexanderianblair commented on bluemira/geometry/optimisation.py
> +def minimise_length(vector, grad, parameterisation, ad_args=None):
Happy with that - this isn't a blocker, by any means

2022-03-21 12:53 UTC, alexanderianblair commented on bluemira/geometry/optimisation.py
> +class GeometryOptimisationProblem(OptimisationProblem):
Sounds good - I think that's the clearest of both options, on balance

2022-03-21 12:56 UTC, alexanderianblair approved these changes
Happy now the comments have been addressed!

2022-03-24 11:54 UTC, je-cook approved these changes

2022-03-31 11:09 UTC, hsaunders1904 requested changes

2022-03-31 11:42 UTC, CoronelBuendia commented on bluemira/builders/EUDEMO/tf_coils.py
> +        self._centreline = parameterisation.create_shape()
Hmm, yeah I suppose the signature should be consistent. What are you suggesting here; just to return the parameterisation in this method? Or something else?

2022-03-31 11:43 UTC, CoronelBuendia commented on bluemira/geometry/optimisation.py
> +__all__ = ("GeometryOptimisationProblem", "minimise_length")
Yes, I've always seen it as a list too. But then I saw somebody using a tuple, and thought an immutable type makes more sense.

2022-03-31 11:54 UTC, hsaunders1904 commented on bluemira/builders/EUDEMO/tf_coils.py
> +        self._centreline = parameterisation.create_shape()
Would what `WallBuilder` does work here? 

I think the equivalent in this case would be:

```python
    super().run(
            params=self._params,
            wp_cross_section=self._wp_cross_section,
            separatrix=self._separatrix,
            keep_out_zone=self._keep_out_zone,
    )
    self._centreline = self._shape.create_shape()
```

2022-03-31 12:01 UTC, CoronelBuendia commented on bluemira/builders/EUDEMO/tf_coils.py
> +        self._centreline = parameterisation.create_shape()
@alexanderianblair felt that we should return the parameterisation from OptimisationProblem but we don't need to do that in the builder base class.

I can put `self._shape = self._design_problem.optimise()` in the base class

2022-03-31 13:04 UTC, hsaunders1904 commented on bluemira/builders/EUDEMO/tf_coils.py
> +        self._centreline = parameterisation.create_shape()
Not sure I'm completely following. `OptimisationProblem.optimise()` is returning the paramterisation...

I'm happy with the state it's in now if you are. If you are happy, there's some commented out code in `bluemira.builders.shapes.OptimisedShapeBuilder.run` that should probably be removed

2022-03-31 13:05 UTC, CoronelBuendia commented on bluemira/builders/EUDEMO/tf_coils.py
> +        self._centreline = parameterisation.create_shape()
ah shit my bad, thanks

2022-03-31 13:10 UTC, hsaunders1904 commented
This has picked up some conflicts, but I'm happy once the CI is

2022-03-31 13:55 UTC, merged