Matti/emulate msh2xdmf
Fusion-Power-Plant-Framework/bluemira pull request #855
Opened 2022-03-24 14:51 UTC by CoronelBuendia

## Linked Issues

Closes #852 

## Description

What is your PR trying to achieve? How did you go about achieving it?

## Interface Changes

If you've had to update an interface or introduce a new interface as part of your change then let us know here.

## Checklist

I confirm that I have completed the following checks:

- [ ] Tests run locally and pass `pytest tests --reactor`
- [ ] Code quality checks run locally and pass `flake8` and `black .`
- [ ] Documentation built locally and checked `sphinx-build -W documentation/source documentation/build`

2022-03-24 15:42 UTC, je-cook commented
will this allow us to re upgrade gmsh?

2022-03-24 18:24 UTC, CoronelBuendia commented
> will this allow us to re upgrade gmsh?

Uff, dunno.. @ivanmaione ?

2022-03-25 05:51 UTC, ivanmaione commented
> > will this allow us to re upgrade gmsh?
> 
> Uff, dunno.. @ivanmaione ?

There should not be problem in upgrade gmsh, if they don't change the way in which physical groups and boundaries are identified. Same for meshio on the format of the cell data (we already got incompatibility with the last version of meshio).

2022-03-25 06:13 UTC, CoronelBuendia commented
> > > will this allow us to re upgrade gmsh?
> > 
> > 
> > Uff, dunno.. @ivanmaione ?
> 
> There should not be problem in upgrade gmsh, if they don't change the way in which physical groups and boundaries are identified. Same for meshio on the format of the cell data (we already got incompatibility with the last version of meshio).

OK, but I think one for another PR once this is in.

2022-03-26 21:15 UTC, ivanmaione requested changes
Just minor comments...

2022-03-26 21:15 UTC, ivanmaione commented on examples/equilibria/fem_fixed_boundary/fem_magnetostatic_2D_single_coil.py
> +    dimensions=(0, 2),
When the files xdmf have been already created, this code would produce the same result for `dimensions=(1,2)`, `dimensions=2`, or `dimensions=(0,1)`. This behavior can be misleading.  A possible solution could be to remove in the `import_mesh` function the possibility to generate the xdmf file:
```
if not os.path.exists(domain_file) or not os.path.exists(boundary_file):
        msh_to_xdmf(f"{file_prefix}.msh", dimensions=dimensions, directory=directory)
```
and to limit `dimensions` to the `mesh.topology().dim()` (i.e. remove `dimensions` from the function signature).

2022-03-28 07:18 UTC, ivanmaione approved these changes

2022-03-28 07:22 UTC, ivanmaione commented
@CoronelBuendia, folder tests/mesh/__pycache__ should be removed.

2022-03-28 07:23 UTC, CoronelBuendia commented
> @CoronelBuendia, folder tests/mesh/**pycache** should be removed.

Ah yeah, thanks. Think I must have force added the folder at some point forgetting about the pycache

2022-03-28 07:51 UTC, ivanmaione approved these changes

2022-03-28 07:51 UTC, merged