Add repo-review team to CODEOWNERS
Fusion-Power-Plant-Framework/bluemira pull request #883
Opened 2022-03-29 11:35 UTC by CoronelBuendia

## Linked Issues

Does this PR close or fix any Issues? Remember to create an Issue before starting work so that your fix / proposal can be addressed by the team.

e.g. Closes #{ID}

## Description

What is your PR trying to achieve? How did you go about achieving it?

## Interface Changes

If you've had to update an interface or introduce a new interface as part of your change then let us know here.

## Checklist

I confirm that I have completed the following checks:

- [ ] Tests run locally and pass `pytest tests --reactor`
- [ ] Code quality checks run locally and pass `flake8` and `black .`
- [ ] Documentation built locally and checked `sphinx-build -W documentation/source documentation/build`

2022-03-29 11:38 UTC, CoronelBuendia commented on CODEOWNERS
> +*/ @Fusion-Power-Plant-Framework/repo-review
I'm intending this to hit everything in the top level directory but NOT sub-directories. Unfortuantely I can't know if this works a priori... @je-cook maybe you know

2022-03-29 11:38 UTC, CoronelBuendia commented on CODEOWNERS
> +*/ @Fusion-Power-Plant-Framework/repo-review
I'm pretty sure this is wrong

2022-03-30 07:36 UTC, je-cook requested changes
I had a look and also couldn't find a nicer way of doing this.

Add versioneer.py too?

2022-03-30 07:49 UTC, je-cook approved these changes

2022-03-31 10:29 UTC, merged