hsaunders1904/add eu demo breeding blanket builder
Fusion-Power-Plant-Framework/bluemira pull request #886
Opened 2022-03-29 12:54 UTC by hsaunders1904

# Work in progress

## Description

Adds a variable thickness blanket to the first wall builder.

I've messed up a rebase somehow, so there are lots of extra commits in this PR, but the files changed are correct. I'll fix the commits issue

## Checklist

I confirm that I have completed the following checks:

- [ ] Tests run locally and pass `pytest tests --reactor`
- [ ] Code quality checks run locally and pass `flake8` and `black .`
- [ ] Documentation built locally and checked `sphinx-build -W documentation/source documentation/build`

2022-03-30 17:11 UTC, hsaunders1904 commented on bluemira/builders/EUDEMO/reactor.py
> -        component.add_child(self.build_first_wall(component))
@CoronelBuendia I pictured calling `build_in_vessel_component_shapes()` here, then using those shapes to call whichever other builders need them. If you had something else in mind, feel free to go with that.

The `build_ivc_xz_shapes()` function will turn the output components of the `IVCBuilder` into the shapes you need

2022-03-31 05:31 UTC, CoronelBuendia requested changes

2022-03-31 05:31 UTC, CoronelBuendia commented on bluemira/builders/EUDEMO/ivc/ivc.py
> +from bluemira.builders.EUDEMO.ivc.blanket import BlanketBuilder
Maybe `IVCThicknessBuilder` or `BlanketThicknessBuilder`?

2022-03-31 05:31 UTC, CoronelBuendia commented on bluemira/builders/EUDEMO/ivc/ivc.py
> +from bluemira.builders.EUDEMO.ivc.divertor import DivertorBuilder
`DivertorSilhouetteBuilder`?

2022-03-31 05:31 UTC, CoronelBuendia commented on bluemira/builders/EUDEMO/reactor.py
> +        return build_ivc_xz_shapes(component, self._params.get_param("c_rm").value)
I normally do `self._params.c_rm.value` not sure if that would work at the reactor level

2022-03-31 05:31 UTC, CoronelBuendia commented on bluemira/builders/EUDEMO/ivc/blanket.py
> +        boundary_wire = varied_offset(self._wall_shape, 1, 2.5, 45, 175)
```suggestion
        boundary_wire = varied_offset(self._wall_shape, self._params.tk_bb_ib.value, self._params.tk_bb_ob.value, 60, 160)
```

2022-03-31 05:31 UTC, CoronelBuendia commented on bluemira/builders/EUDEMO/ivc/blanket.py
> +
Don't we need `_required_params = [..]` here?

2022-03-31 12:40 UTC, merged