EUDEMO upper port size optimisation problem
Fusion-Power-Plant-Framework/bluemira pull request #922
Opened 2022-04-05 15:44 UTC by CoronelBuendia

## Linked Issues

Starting to address #906 

## Description

What is your PR trying to achieve? How did you go about achieving it?

## Interface Changes

If you've had to update an interface or introduce a new interface as part of your change then let us know here.

## Checklist

I confirm that I have completed the following checks:

- [ ] Tests run locally and pass `pytest tests --reactor`
- [ ] Code quality checks run locally and pass `flake8` and `black .`
- [ ] Documentation built locally and checked `sphinx-build -W documentation/source documentation/build`

2022-04-13 14:18 UTC, hsaunders1904 requested changes
Code looks pretty good to me. Only a few nitpicks, we're also missing tests.

2022-04-13 14:18 UTC, hsaunders1904 commented on bluemira/builders/EUDEMO/maintenance.py
> +                tolerance=1e-6 * np.ones(3),
I'm not clear where this 3 comes from, I guess it's the number of constraints? Maybe another one to extract into a variable?

2022-04-14 10:23 UTC, hsaunders1904 reviewed
A couple of minor comments to finish

2022-04-14 10:23 UTC, hsaunders1904 commented on bluemira/builders/EUDEMO/maintenance.py
> +    # TODO: Remove this once threaded into the reactor build via some kind of builder
Do we have an issue that resolves this TODO? If there's an existing issue, is it explicit about removing this?

2022-04-14 11:38 UTC, hsaunders1904 approved these changes

2022-04-14 11:38 UTC, hsaunders1904 commented on bluemira/builders/EUDEMO/maintenance.py
> +    r_up_inner: radius
Is `radius` a type, or should this be `float`? 

Happy for this to be merged once this is fixed

2022-04-14 11:54 UTC, je-cook reviewed
Just one minor from me

2022-04-14 11:54 UTC, je-cook commented on bluemira/builders/EUDEMO/maintenance.py
> +                tolerance=1e-6 * np.ones(n_constraints),
Is it overkill to make this tolerance configurable? Or maybe just 0.1*geometry.constants.MINIMUM_LENGTH

2022-04-14 13:42 UTC, je-cook approved these changes

2022-04-14 13:43 UTC, merged